name: drop_bites
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+2
  animated_text_kit: ^2.0.0
  flutter_spinkit: ^4.1.2
  http: ^0.12.0+4
  provider: ^4.0.4
  font_awesome_flutter: ^8.7.0
  intl: ^0.16.1
  image_picker: ^0.6.4
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.2.0+1
  google_maps_flutter: ^0.5.27+3
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  random_string: ^2.0.1
  flutter_circular_slider: ^2.5.0
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/

  fonts:
    - family: Dekko
      fonts:
        - asset: fonts/Dekko-Regular.ttf

    - family: Slabo
      fonts:
        - asset: fonts/Slabo27px-Regular.ttf

    - family: Rokkitt
      fonts:
        - asset: fonts/Rokkitt-Regular.ttf
